### ISSUE TITLE
Set Item Quantity from Quantity(F2) textfield

### ISSUE THREAD

**Issue by elliegoldstein8** [paranzchoy/rapidpos#189]
Flow:
 			- User presses F2
 			- User inputs quantity
 			- User presses F3 and scans item barcode/user clicks an item from the Item List
 			- System should set the quantity to the item

- [x] Set quantity on item barcode
- [x] Set quantity on item selection

**Comment by paranzchoy** [comment]
@elliegoldstein8 @JMBodz 

What is the status of this issue? Naa na mo fix?

**Comment by JMBodz** [comment]
On my local VM this works. no changes made from the repo.
- [x] - User presses F2
- [x] - User inputs quantity
- [x] - User presses F3 and scans item barcode
- [x] - User Clicks an item from the Item List

**Comment by JMBodz** [comment]
Still on Progress:
Cashier Press F2 and inputs quantity, then select item from the item field. Item goes to card with the quantity from the quantity field
