### ISSUE TITLE
Discount Type (Senior/PWD)

### ISSUE THREAD

**Issue by elliegoldstein8** [paranzchoy/rapidpos#192]
- [x]  Redesign suitable doctype with a table for percentages each discount type and shop category (Item Groups: Food/Grocery and Pharmacy/Medical)
        - Senior & PWD data is currently added at Additional Discount Type doctype.
        - Senior & PWD : Grocery = 5% discount
        - Senior & PWD : Pharmacy = 20% discount
- [x] Change code according to data model
        - Identifying Food & Grocery Item Groups are hardcoded in Invoice.vue.

**Comment by paranzchoy** [comment]
Additional Discount Type (doctype):
Add additional fields:
- default percentage (ex. 5%)
- child table linked to item group
         - item group
         - percentage (optional)
         - example:
 - example: 
         - Name:Senior Citizen Discount:
         - Discount Type: SRCTZN
         - Description: kgkygy
         - Default %: 5%
         - Child Table: (Item Group)        
                  1. food/grocery - (empty)
                  2. medicine - 20%

**Comment by paranzchoy** [comment]
additional Todo:
- [ ] Update doctype
- [ ] Refac POS code
