### ISSUE TITLE
Create sales invoice print layout as sales order

### ISSUE THREAD

**Issue by paranzchoy** [paranzchoy/rapidpos#200]
This is a feature request from Jacobs Breadnuts.

When receipt is printed, it should show Sales Order instead of Sales Invoice.

**Comment by paranzchoy** [comment]
Sample receipt given by Jay:

![242428180_898807357681284_9163122330798056935_n](https://user-images.githubusercontent.com/74954036/135971938-c2f70f82-ef7a-4d3f-b4a4-5e48a8ed39a0.jpg)

**Comment by paranzchoy** [comment]
@Thirdyyyyyyy 

Pls post the required customizations here

**Comment by Thirdyyyyyyy** [comment]
sales receipt - sales order, add with date
Bill to - ordered by
up to subtotal only
cashier - in-charge
remove store: que
move at the bottom: this is not an official receipt
Add note: Please ask official receipt at the counter upon payment

**Comment by paranzchoy** [comment]
@Thirdyyyyyyy 

Pls create user interface diagram in EA for this custom receipt layout.

**Comment by Thirdyyyyyyy** [comment]
![image](https://user-images.githubusercontent.com/67768594/135977160-81951a4c-ad17-4aa4-91f0-f41402df6d84.png)

**Comment by Thirdyyyyyyy** [comment]
![image](https://user-images.githubusercontent.com/67768594/136137999-8b8494b6-6678-41b7-bc97-4833b37be7b7.png)
Sales Order Receipt Version1
@paranzchoy

**Comment by elliegoldstein8** [comment]
Receipt format (as reviewed by Henry):
![image](https://user-images.githubusercontent.com/50741638/141041574-76f7c6a8-3e06-426b-bb54-4c9bae7f2974.png)
- added subtotal, discount, grand total, payment and change fields
Connected to issue #195 which is already closed.
