### ISSUE TITLE
[BUG]: NO DISCOUNT DETAILS in Accounting - Chart of Accounts

### ISSUE THREAD

**Issue by JMBodz** [paranzchoy/rapidpos#209]
No Discount details when Pricing Rule, Coupon Code and Discount types are used.

**Comment by JMBodz** [comment]
No Account in Chart of Accounts for Discounts

**Comment by elliegoldstein8** [comment]
ERPNext recently added Discount Accounting to their documentation just yesterday evening:
![image](https://user-images.githubusercontent.com/50741638/141036704-26be8e37-7ca0-491d-a266-18af8a42a897.png)
Link: https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/discount_accounting
Just follow the instructions and the discount will be debited to the Discount Account:
![image](https://user-images.githubusercontent.com/50741638/141036854-5eec6e40-9f8d-42bc-a27e-147620cdfc62.png)

**Comment by elliegoldstein8** [comment]
Marking this as solved.
